<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_SINT_TO_SINT" Id="{45b821e5-e453-4460-b645-f53fcb17bd60}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_SINT_TO_SINT : Hresult
VAR_INPUT
	in : SINT;
	out : REFERENCE TO SINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>