<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_ULINT_TO_ULINT" Id="{cc21abea-80c4-4a9a-93f6-5cf0ecbe4767}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_ULINT_TO_ULINT : Hresult
VAR_INPUT
	in : ULINT;
	out : REFERENCE TO ULINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>