<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_DT_TO_DT" Id="{2cf209c1-c3f7-47c9-8ec9-ba0ad1566d33}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_DT_TO_DT : Hresult
VAR_INPUT
	in : DT;
	out : REFERENCE TO DT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>