<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="ReturnNamespaceFromInstancePath" Id="{b039a93c-9431-4db4-aae4-79d95ea7f415}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ReturnNamespaceFromInstancePath : STRING
VAR_INPUT
	InstancePath : T_MAXSTRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[ReturnNamespaceFromInstancePath := ReturnSubSectionFromInstancePath(InstancePath,3);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>