<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_LREAL_TO_LREAL" Id="{3c9aeadf-fbe1-42f5-80b7-fbf69cd10dd4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_LREAL_TO_LREAL : Hresult
VAR_INPUT
	in : LREAL;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>