<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_DATE_TO_DATE" Id="{7116e533-ce53-4987-a18b-0d0381f360a2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_DATE_TO_DATE : Hresult
VAR_INPUT
	in : DATE;
	out : REFERENCE TO DATE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>