<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="CyclicInstance" Id="{dc2e84c3-6d56-43a2-a4f0-a82e4ef40050}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'}
{attribute 'no_explicit_call' := 'do not call this POU directly'}
FUNCTION_BLOCK ABSTRACT CyclicInstance EXTENDS Instance IMPLEMENTS I_CyclicInstance
VAR
	membership : AutomaticGlobalInstanceMembership(THIS^);
	_cyclicInstanceCallback : CyclicCallback(THIS^);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Abstract" Id="{25661d79-aab9-4fb7-bdb4-976335c48e7a}" />
    <Method Name="CyclicCall" Id="{88412bc0-cc27-4015-9d40-0dabd1437f7c}" FolderPath="Abstract\">
      <Declaration><![CDATA[METHOD ABSTRACT CyclicCall
VAR_INPUT
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="CyclicInstanceCallback" Id="{2fedc0eb-3da0-43a8-8555-691afde2d4a4}">
      <Declaration><![CDATA[PROPERTY PUBLIC CyclicInstanceCallback : I_Callback]]></Declaration>
      <Get Name="Get" Id="{49d5d242-2da3-436f-b409-782c762f0a38}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[CyclicInstanceCallback := _cyclicInstanceCallback;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>