<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_BYTE_TO_BYTE" Id="{3651e0ca-315f-40cb-9605-11cd5d5370b9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_BYTE_TO_BYTE : Hresult
VAR_INPUT
	in : BYTE;
	out : REFERENCE TO BYTE;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>