<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_TOD_TO_TOD" Id="{f63c2af7-0cef-447c-9c59-4bcc504531f9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_TOD_TO_TOD : Hresult
VAR_INPUT
	in : TOD;
	out : REFERENCE TO TOD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>