<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="CyclicInstance" Id="{dc2e84c3-6d56-43a2-a4f0-a82e4ef40050}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'}
{attribute 'no_explicit_call' := 'do not call this POU directly'}
FUNCTION_BLOCK ABSTRACT CyclicInstance EXTENDS Instance IMPLEMENTS I_CyclicCalled
VAR
	cyclicCall : AutomaticCyclicCall(THIS^);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Abstract" Id="{25661d79-aab9-4fb7-bdb4-976335c48e7a}" />
    <Method Name="CyclicCall" Id="{88412bc0-cc27-4015-9d40-0dabd1437f7c}" FolderPath="Abstract\">
      <Declaration><![CDATA[METHOD ABSTRACT CyclicCall
VAR_INPUT
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>