<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_LINT_TO_LINT" Id="{813533c2-dd09-4be9-b330-8fad9215e075}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_LINT_TO_LINT : Hresult
VAR_INPUT
	in : LINT;
	out : REFERENCE TO LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>