<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TEST_PRG" Id="{b5c953e6-7c7b-0766-2ee7-4c71c052c057}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST_PRG
VAR
	jsonPath_Test : JsonPath_TestSuit;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[jsonPath_Test();

TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>