<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_REAL_TO_REAL" Id="{7ac5fd4e-0228-4550-918e-c1d9a60673d8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_REAL_TO_REAL : Hresult
VAR_INPUT
	in : REAL;
	out : REFERENCE TO REAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>