<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_REAL_TO_LREAL" Id="{2cda2b08-9535-4a1f-84c0-80296f6667b5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_REAL_TO_LREAL : Hresult
VAR_INPUT
	in : REAL;
	out : REFERENCE TO LREAL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := REAL_TO_LREAL(in);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>