<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_BOOL_TO_BOOL" Id="{341db262-657a-47f7-b21b-8c55f4236a6b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_BOOL_TO_BOOL : Hresult
VAR_INPUT
	in : BOOL;
	out : REFERENCE TO BOOL;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>