<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_INT_TO_INT" Id="{c0658139-c7ff-43cd-bb59-d25e3a145356}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_INT_TO_INT : Hresult
VAR_INPUT
	in : INT;
	out : REFERENCE TO INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>