<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_USINT_TO_USINT" Id="{e1a5c736-8be1-4628-b126-4e1b90b95e21}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_USINT_TO_USINT : Hresult
VAR_INPUT
	in : USINT;
	out : REFERENCE TO USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>