<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_WORD_TO_WORD" Id="{842ab4a9-8d5d-4348-b1c5-f9b8c055a620}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_WORD_TO_WORD : Hresult
VAR_INPUT
	in : WORD;
	out : REFERENCE TO WORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>