<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_STRING_TO_STRING" Id="{6ebf981a-8a24-4c6f-976b-5a35dd93fe19}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_STRING_TO_STRING : Hresult
VAR_INPUT
	in : STRING;
	out : REFERENCE TO STRING;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>