<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Convert_DINT_TO_DINT" Id="{d3973cea-76fe-4516-bfc1-1a95b550579a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Convert_DINT_TO_DINT : Hresult
VAR_INPUT
	in : DINT;
	out : REFERENCE TO DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[out := in;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>