<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_SafeRelease" Id="{103e1eb7-716e-0044-2f6e-badb145686c4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_SafeRelease
VAR_INPUT
	Object : I_Disposable;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF Object <> 0 THEN
	Object.Release();
END_IF]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>