<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="GlobalInstanceMembership" Id="{5379c42d-60b0-0f96-2707-1e7024be9f53}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK GlobalInstanceMembership
VAR
	self : I_Instance;
	globalInstanceMembers : GlobalInstanceMembers;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{e262ff51-644b-0506-0508-703417503d68}" />
    <Folder Name="Destructor" Id="{54e23e08-eb90-06f9-0fc7-211f64d8b012}" />
    <Method Name="FB_exit" Id="{390afa1a-ce99-0e3d-1805-8e3dbf7e9ca4}" FolderPath="Destructor\">
      <Declaration><![CDATA[METHOD FB_exit : BOOL
VAR_INPUT
	bInCopyCode : BOOL; // if TRUE, the exit method is called for exiting an instance that is copied afterwards (online change).
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Leave();]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{837f29a6-641f-011f-312e-38a2f67f12aa}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	Self : I_Instance;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.self := Self;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Join" Id="{1751e7f1-20f7-08fc-07bf-287f2e5bfc45}">
      <Declaration><![CDATA[METHOD PUBLIC Join
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[globalInstanceMembers.AddInstance(Self);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Leave" Id="{9e38e006-a362-051a-0a76-7aae16685823}">
      <Declaration><![CDATA[METHOD PUBLIC Leave
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[globalInstanceMembers.RemoveInstance(THIS^.self);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>